In [1]:
pip install pandas sqlalchemy psycopg2-binary

Requirement already satisfied: pandas in D:\Python\Lib\site-packages (3.0.3)
Requirement already satisfied: sqlalchemy in D:\Python\Lib\site-packages (2.0.51)
Requirement already satisfied: psycopg2-binary in D:\Python\Lib\site-packages (2.9.12)
Requirement already satisfied: numpy>=1.26.0 in D:\Python\Lib\site-packages (from pandas) (2.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in D:\Python\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in D:\Python\Lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: greenlet>=1 in D:\Python\Lib\site-packages (from sqlalchemy) (3.5.3)
Requirement already satisfied: typing-extensions>=4.6.0 in D:\Python\Lib\site-packages (from sqlalchemy) (4.15.0)
Requirement already satisfied: six>=1.5 in D:\Python\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
from sqlalchemy import create_engine
import pandas as pd

In [4]:
#for connecting to engine
engine = create_engine(
    "postgresql://postgres:1234@localhost:5432/online_retail_db"
)

In [5]:
query = """
SELECT *
FROM customers
LIMIT 5;
"""

pd.read_sql(query, engine)

,customer_id,full_name,email,phone,country,signup_date,signup_channel,loyalty_points
0,1,Customer 1,customer1@email.com,+91-9000000001,USA,2025-12-17,Website,5
1,2,Customer 2,customer2@email.com,+91-9000000002,UK,2025-12-16,Mobile App,10
2,3,Customer 3,customer3@email.com,+91-9000000003,Germany,2025-12-15,Website,15
3,4,Customer 4,customer4@email.com,+91-9000000004,India,2025-12-14,Mobile App,20
4,5,Customer 5,customer5@email.com,+91-9000000005,USA,2025-12-13,Website,25

# Online Retail Analytics

## SQL Capstone Project

### Objective

This project analyzes an online retail company's data to understand:

- Customer behavior
- Product performance
- Sales and revenue trends
- Customer retention
- Order fulfillment
- Payment behavior

In [6]:
#database connection
from sqlalchemy import create_engine
import pandas as pd

engine = create_engine(
    "postgresql://postgres:1234@localhost:5432/online_retail_db"
)

In [7]:
#function to run query
def run_query(query):
    return pd.read_sql(query, engine)

### Q1. Retrieve top 5 highest value completed orders (order_id, customer_id, order_amount, order_date)

In [8]:
query = """
SELECT
    o.order_id,
    o.customer_id,
    SUM(oi.quantity * oi.unit_price) AS order_amount,
    o.order_date
FROM orders o
JOIN order_items oi
    ON o.order_id = oi.order_id
WHERE o.status = 'Completed'
GROUP BY
    o.order_id,
    o.customer_id,
    o.order_date
ORDER BY order_amount DESC
LIMIT 5;
"""

run_query(query)

   order_id  customer_id  order_amount  order_date
0       300          301       4994.55  2025-11-18
1       795          796       4987.75  2025-10-04
2        45           46       4846.60  2025-11-03
3       180          181       4833.15  2025-12-18
4        15           16       4760.50  2025-12-03

### Q2. List customers with more than 2 orders (customer_id, full_name, total_orders)

In [9]:
query = """
SELECT
    c.customer_id,
    c.full_name,
    COUNT(o.order_id) AS total_orders
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
GROUP BY
    c.customer_id,
    c.full_name
HAVING COUNT(o.order_id) > 2
ORDER BY total_orders DESC;
"""

run_query(query)

Empty DataFrame
Columns: [customer_id, full_name, total_orders]
Index: []

### Q3: Get customers who never placed an order using LEFT JOIN (customer_id, full_name, signup_date)

In [10]:
query = """
SELECT
    c.customer_id,
    c.full_name,
    c.signup_date
FROM customers c
LEFT JOIN orders o
    ON c.customer_id = o.customer_id
WHERE o.order_id IS NULL;
"""

run_query(query)

Empty DataFrame
Columns: [customer_id, full_name, signup_date]
Index: []

### Q4: Show most expensive product purchased by each customer (customer_id, product_name, price)

In [18]:
query = """
WITH ranked_products AS (
    SELECT
        o.customer_id,
        p.product_name,
        p.price,
        ROW_NUMBER() OVER (
            PARTITION BY o.customer_id
            ORDER BY p.price DESC
        ) AS product_rank
    FROM orders o
    JOIN order_items oi
        ON o.order_id = oi.order_id
    JOIN products p
        ON oi.product_id = p.product_id
)

SELECT
    customer_id,
    product_name,
    price
FROM ranked_products
WHERE product_rank = 1;
"""

run_query(query)

     customer_id  product_name   price
0              1  Product 1000  952.00
1              2     Product 1  425.43
2              3     Product 2  224.45
3              4     Product 3  315.16
4              5     Product 4  944.79
..           ...           ...     ...
994          996   Product 995  668.55
995          997   Product 996  354.93
996          998   Product 997  629.16
997          999   Product 998  909.16
998         1000   Product 999  318.47

[999 rows x 3 columns]

### Q5: Find order with largest number of items (order_id, total_items)

In [19]:
query = """
SELECT
    order_id,
    SUM(quantity) AS total_items
FROM order_items
GROUP BY order_id
ORDER BY total_items DESC
LIMIT 1;
"""

run_query(query)

   order_id  total_items
0        70            5

### Q6: List customers who ordered within 30 days of signup (customer_id, full_name, signup_date, first_order_date, days_difference)

In [23]:
query = """
WITH first_orders AS (
    SELECT
        customer_id,
        MIN(order_date) AS first_order_date
    FROM orders
    GROUP BY customer_id
)

SELECT
    c.customer_id,
    c.full_name,
    c.signup_date,
    f.first_order_date,
    f.first_order_date - c.signup_date AS days_difference
FROM customers c
JOIN first_orders f
    ON c.customer_id = f.customer_id
WHERE f.first_order_date - c.signup_date BETWEEN 0 AND 30;
"""

run_query(query)

    customer_id    full_name signup_date first_order_date  days_difference
0             2   Customer 2  2025-12-16       2025-12-17                1
1             3   Customer 3  2025-12-15       2025-12-16                1
2             4   Customer 4  2025-12-14       2025-12-15                1
3             5   Customer 5  2025-12-13       2025-12-14                1
4             6   Customer 6  2025-12-12       2025-12-13                1
..          ...          ...         ...              ...              ...
84           86  Customer 86  2025-09-23       2025-09-24                1
85           87  Customer 87  2025-09-22       2025-09-23                1
86           88  Customer 88  2025-09-21       2025-09-22                1
87           89  Customer 89  2025-09-20       2025-09-21                1
88           90  Customer 90  2025-09-19       2025-09-20                1

[89 rows x 5 columns]

### Q7: Count orders per status per country (country, status, order_count)

In [20]:
query = """
SELECT
    c.country,
    o.status,
    COUNT(o.order_id) AS order_count
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
GROUP BY
    c.country,
    o.status
ORDER BY
    c.country,
    o.status;
"""

run_query(query)

    country     status  order_count
0   Germany  Cancelled           83
1   Germany  Completed           83
2   Germany    Pending           84
3     India  Cancelled           83
4     India  Completed           84
5     India    Pending           83
6        UK  Cancelled           84
7        UK  Completed           83
8        UK    Pending           83
9       USA  Cancelled           84
10      USA  Completed           83
11      USA    Pending           83

### Q8: Calculate Customer Lifetime Value (customer_id, full_name, total_revenue)

In [24]:
query = """
SELECT
    c.customer_id,
    c.full_name,
    SUM(oi.quantity * oi.unit_price) AS total_revenue
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
JOIN order_items oi
    ON o.order_id = oi.order_id
GROUP BY
    c.customer_id,
    c.full_name
ORDER BY total_revenue DESC;
"""

run_query(query)

     customer_id     full_name  total_revenue
0            301  Customer 301        4994.55
1            796  Customer 796        4987.75
2            591  Customer 591        4974.25
3            641  Customer 641        4963.85
4            431  Customer 431        4923.50
..           ...           ...            ...
995          492  Customer 492         119.27
996          182  Customer 182         119.02
997          717  Customer 717         109.68
998          502  Customer 502         106.12
999          187  Customer 187         103.25

[1000 rows x 3 columns]

### Q9: Identify repeat customers - more than 1 order per month (customer_id, full_name, order_month, monthly_order_count)

In [25]:
query = """
SELECT
    c.customer_id,
    c.full_name,
    DATE_TRUNC('month', o.order_date)::DATE AS order_month,
    COUNT(o.order_id) AS monthly_order_count
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
GROUP BY
    c.customer_id,
    c.full_name,
    DATE_TRUNC('month', o.order_date)
HAVING COUNT(o.order_id) > 1
ORDER BY
    c.customer_id,
    order_month;
"""

run_query(query)

Empty DataFrame
Columns: [customer_id, full_name, order_month, monthly_order_count]
Index: []

### Q10: Monthly revenue trend (year, month, total_revenue)

In [26]:
query = """
SELECT
    EXTRACT(YEAR FROM o.order_date) AS year,
    EXTRACT(MONTH FROM o.order_date) AS month,
    SUM(oi.quantity * oi.unit_price) AS total_revenue
FROM orders o
JOIN order_items oi
    ON o.order_id = oi.order_id
WHERE o.status = 'Completed'
GROUP BY
    EXTRACT(YEAR FROM o.order_date),
    EXTRACT(MONTH FROM o.order_date)
ORDER BY
    year,
    month;
"""

run_query(query)

     year  month  total_revenue
0  2025.0    9.0       44210.62
1  2025.0   10.0      217678.86
2  2025.0   11.0      192722.49
3  2025.0   12.0      122206.35

### Q11: Most returned products where status=Returned (product_id, product_name, return_count)

In [11]:
query = """
SELECT
    p.product_id,
    p.product_name,
    COUNT(*) AS return_count
FROM orders o
JOIN order_items oi
    ON o.order_id = oi.order_id
JOIN products p
    ON oi.product_id = p.product_id
WHERE o.status = 'Returned'
GROUP BY
    p.product_id,
    p.product_name
ORDER BY
    return_count DESC;
"""

run_query(query)

Empty DataFrame
Columns: [product_id, product_name, return_count]
Index: []

### Q12: Top 3 revenue-generating categories (category, total_revenue)

In [13]:
query = """
SELECT
    p.category,
    SUM(oi.quantity * oi.unit_price) AS total_revenue
FROM orders o
JOIN order_items oi
    ON o.order_id = oi.order_id
JOIN products p
    ON oi.product_id = p.product_id
WHERE o.status = 'Completed'
GROUP BY
    p.category
ORDER BY
    total_revenue DESC
LIMIT 3;
"""

run_query(query)

      category  total_revenue
0  Electronics      180713.10
1      Grocery      157057.24
2        Books      125883.87

### Q13: Products frequently bought together - basket analysis (product_id_1, product_id_2, times_bought_together)

In [14]:
query = """
SELECT
    oi1.product_id AS product_id_1,
    oi2.product_id AS product_id_2,
    COUNT(*) AS times_bought_together
FROM order_items oi1
JOIN order_items oi2
    ON oi1.order_id = oi2.order_id
    AND oi1.product_id < oi2.product_id
GROUP BY
    oi1.product_id,
    oi2.product_id
ORDER BY
    times_bought_together DESC;
"""

run_query(query)

Empty DataFrame
Columns: [product_id_1, product_id_2, times_bought_together]
Index: []

### Q14: Customer retention - ordered again within 90 days (customer_id, full_name, first_order_date, next_order_date, days_between_orders)

In [15]:
query = """
WITH customer_orders AS (
    SELECT
        c.customer_id,
        c.full_name,
        o.order_date AS first_order_date,
        LEAD(o.order_date) OVER (
            PARTITION BY c.customer_id
            ORDER BY o.order_date
        ) AS next_order_date
    FROM customers c
    JOIN orders o
        ON c.customer_id = o.customer_id
)

SELECT
    customer_id,
    full_name,
    first_order_date,
    next_order_date,
    (next_order_date - first_order_date) AS days_between_orders
FROM customer_orders
WHERE
    next_order_date IS NOT NULL
    AND (next_order_date - first_order_date) <= 90
ORDER BY
    customer_id,
    first_order_date;
"""

run_query(query)

Empty DataFrame
Columns: [customer_id, full_name, first_order_date, next_order_date, days_between_orders]
Index: []

### Q16: Discount Sensitivity - customers who only order with discounts (customer_id, full_name, total_orders, discounted_orders)

In [17]:
query = """
SELECT
    c.customer_id,
    c.full_name,
    COUNT(o.order_id) AS total_orders,
    COUNT(CASE
        WHEN o.discount_amount IS NOT NULL THEN 1
    END) AS discounted_orders
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
GROUP BY
    c.customer_id,
    c.full_name
HAVING
    COUNT(o.order_id) =
    COUNT(CASE
        WHEN o.discount_amount IS NOT NULL THEN 1
    END);
"""

run_query(query)

     customer_id     full_name  total_orders  discounted_orders
0            652  Customer 652             1                  1
1            273  Customer 273             1                  1
2             51   Customer 51             1                  1
3            951  Customer 951             1                  1
4            839  Customer 839             1                  1
..           ...           ...           ...                ...
995           64   Customer 64             1                  1
996           55   Customer 55             1                  1
997          148  Customer 148             1                  1
998          790  Customer 790             1                  1
999          828  Customer 828             1                  1

[1000 rows x 4 columns]

### Q17: First vs Most Recent Purchase Product using ROW_NUMBER (customer_id, first_product_name, last_product_name)

In [18]:
query = """
WITH ranked_orders AS (
    SELECT
        o.customer_id,
        p.product_name,
        o.order_date,
        ROW_NUMBER() OVER (
            PARTITION BY o.customer_id
            ORDER BY o.order_date
        ) AS first_rn,
        ROW_NUMBER() OVER (
            PARTITION BY o.customer_id
            ORDER BY o.order_date DESC
        ) AS last_rn
    FROM orders o
    JOIN order_items oi
        ON o.order_id = oi.order_id
    JOIN products p
        ON oi.product_id = p.product_id
)

SELECT
    customer_id,
    MAX(CASE
            WHEN first_rn = 1 THEN product_name
        END) AS first_product_name,
    MAX(CASE
            WHEN last_rn = 1 THEN product_name
        END) AS last_product_name
FROM ranked_orders
GROUP BY customer_id
ORDER BY customer_id;
"""

run_query(query)

     customer_id first_product_name last_product_name
0              1       Product 1000      Product 1000
1              2          Product 1         Product 1
2              3          Product 2         Product 2
3              4          Product 3         Product 3
4              5          Product 4         Product 4
..           ...                ...               ...
994          996        Product 995       Product 995
995          997        Product 996       Product 996
996          998        Product 997       Product 997
997          999        Product 998       Product 998
998         1000        Product 999       Product 999

[999 rows x 3 columns]

### Q18: Revenue Contribution Pareto Analysis - top customers for 80% revenue (customer_id, full_name, customer_revenue, cumulative_revenue, cumulative_percentage)

In [19]:
query = """
WITH customer_revenue AS (
    SELECT
        c.customer_id,
        c.full_name,
        SUM(oi.quantity * oi.unit_price) AS customer_revenue
    FROM customers c
    JOIN orders o
        ON c.customer_id = o.customer_id
    JOIN order_items oi
        ON o.order_id = oi.order_id
    GROUP BY
        c.customer_id,
        c.full_name
),

revenue_rank AS (
    SELECT
        *,
        SUM(customer_revenue)
            OVER (
                ORDER BY customer_revenue DESC
            ) AS cumulative_revenue,
        SUM(customer_revenue)
            OVER () AS total_revenue
    FROM customer_revenue
)

SELECT
    customer_id,
    full_name,
    customer_revenue,
    cumulative_revenue,
    ROUND(
        cumulative_revenue * 100.0 / total_revenue,
        2
    ) AS cumulative_percentage
FROM revenue_rank
WHERE cumulative_revenue * 100.0 / total_revenue <= 80
ORDER BY customer_revenue DESC;
"""

run_query(query)

,customer_id,full_name,customer_revenue,cumulative_revenue,cumulative_percentage
0,301,Customer 301,4994.55,4994.55,0.29
1,796,Customer 796,4987.75,9982.30,0.59
2,591,Customer 591,4974.25,14956.55,0.88
3,641,Customer 641,4963.85,19920.40,1.17
4,431,Customer 431,4923.50,24843.90,1.46
...,...,...,...,...,...
508,958,Customer 958,1418.78,1357928.05,79.61
509,689,Customer 689,1410.24,1359338.29,79.69
510,771,Customer 771,1408.45,1360746.74,79.78
511,440,Customer 440,1407.84,1362154.58,79.86
512,343,Customer 343,1407.14,1363561.72,79.94

### Q19: Brand Affinity per Customer (customer_id, brand, brand_revenue)

In [22]:
query = """
SELECT
    o.customer_id,
    p.brand,
    SUM(oi.quantity * oi.unit_price) AS brand_revenue
FROM orders o
JOIN order_items oi
    ON o.order_id = oi.order_id
JOIN products p
    ON oi.product_id = p.product_id
GROUP BY
    o.customer_id,
    p.brand
ORDER BY
    o.customer_id,
    brand_revenue DESC;
"""

run_query(query)

     customer_id     brand  brand_revenue
0              1   Brand 0        4760.00
1              2   Brand 1         425.43
2              3   Brand 2         448.90
3              4   Brand 3         945.48
4              5   Brand 4        3779.16
..           ...       ...            ...
994          996  Brand 15        3342.75
995          997  Brand 16         354.93
996          998  Brand 17        1258.32
997          999  Brand 18        2727.48
998         1000  Brand 19        1273.88

[999 rows x 3 columns]

### Q20: Payment Failure Impact - orders with failed then successful payment (order_id, customer_id, failed_attempts, successful_payment_date)

In [21]:
query = """
SELECT
    o.order_id,
    o.customer_id,

    COUNT(
        CASE
            WHEN p.payment_status='Failed'
            THEN 1
        END
    ) AS failed_attempts,

    MAX(
        CASE
            WHEN p.payment_status='Completed'
            THEN p.payment_date
        END
    ) AS successful_payment_date

FROM orders o

JOIN payments p
ON o.order_id = p.order_id

GROUP BY
    o.order_id,
    o.customer_id

HAVING
COUNT(
    CASE
        WHEN p.payment_status='Failed'
        THEN 1
    END
) > 0

AND

COUNT(
    CASE
        WHEN p.payment_status='Completed'
        THEN 1
    END
) > 0;
"""

run_query(query)

Empty DataFrame
Columns: [order_id, customer_id, failed_attempts, successful_payment_date]
Index: []

### Q21: Customer Order Velocity - avg days between orders (customer_id, full_name, total_orders, avg_days_between_orders)

In [20]:
query = """
WITH order_gaps AS (
    SELECT
        c.customer_id,
        c.full_name,
        o.order_date,
        LAG(o.order_date) OVER (
            PARTITION BY c.customer_id
            ORDER BY o.order_date
        ) AS previous_order_date
    FROM customers c
    JOIN orders o
        ON c.customer_id = o.customer_id
)

SELECT
    customer_id,
    full_name,
    COUNT(*) AS total_orders,
    AVG(order_date - previous_order_date) AS avg_days_between_orders
FROM order_gaps
GROUP BY
    customer_id,
    full_name
ORDER BY
    customer_id;
"""

run_query(query)

     customer_id      full_name  total_orders avg_days_between_orders
0              1     Customer 1             1                    None
1              2     Customer 2             1                    None
2              3     Customer 3             1                    None
3              4     Customer 4             1                    None
4              5     Customer 5             1                    None
..           ...            ...           ...                     ...
995          996   Customer 996             1                    None
996          997   Customer 997             1                    None
997          998   Customer 998             1                    None
998          999   Customer 999             1                    None
999         1000  Customer 1000             1                    None

[1000 rows x 4 columns]